CREATE database if not exists project_db;
USE project_db;
CREATE TABLE if not exists survey ()
id INT AUTO_INCREMENT PRIMARY KEY,
full_name VARCHAR(100), NOT NULL,
email VARCHAR(120) NOT NULL,
PHONE VARCHAR(15) NOT NULL,
age INT NOT NULL,
CONUNTRY VARCHAR(50) NOT NULL
,
EXPERIENCE_LEVEL VARCHAR(50) NOT NULL,
NEWSLETTER_VARCHAR(10) NOT NULL,
COMMENTS VARCHAR(255) not null,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

